# Generated by Django 3.2.9 on 2021-11-09 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casinos', '0002_rename_wallet_casino_account'),
        ('players', '0002_rename_wallet_player_account'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='Account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_wallet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='payments.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='payments.account'),
            preserve_default=False,
        ),
    ]
