# Generated by Django 3.2.9 on 2021-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentgateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Casino'), (1, 'Player'), (2, 'Payment Gateway')]),
        ),
    ]
