# Generated by Django 3.2.9 on 2021-11-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='bet_time',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bettype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='thrown_number',
        ),
        migrations.AlterField(
            model_name='bet',
            name='bet_amount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.transaction'),
        ),
        migrations.AlterField(
            model_name='bettype',
            name='win_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='GameTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(null=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
