# Generated by Django 3.2.9 on 2021-11-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20211109_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='bet_amount',
            new_name='transaction',
        ),
    ]
