# Generated by Django 3.2.9 on 2021-11-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_bet_game'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameResult',
            new_name='BallThrow',
        ),
        migrations.RenameField(
            model_name='ballthrow',
            old_name='result',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='gametime',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Start'), (0, 'End')]),
        ),
    ]
