# Generated by Django 3.2.9 on 2021-11-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20211109_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='number',
            new_name='bet_number',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='bet_type',
        ),
        migrations.DeleteModel(
            name='BetType',
        ),
    ]
