# Generated by Django 3.2.9 on 2021-11-09 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20211109_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='casino',
        ),
    ]
