# Generated by Django 3.2.9 on 2021-11-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='wallet',
            new_name='account',
        ),
    ]
